<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // ================= HP =================
            [
                'name' => 'Samsung Galaxy S23',
                'brand' => 'Samsung',
                'image' => 'img/category/samsung-s23.png',
                'old_price' => 15000000,
                'price' => 14000000,
                'discount' => 7,
                'stock' => 'tersedia',
                'specs' => 'Snapdragon 8 Gen 2, RAM 8GB, 256GB Storage',
                'category' => 'hp',
                'level' => 'flagship',
                'section' => 'recommendation',
            ],
            [
                'name' => 'iPhone 14 Pro',
                'brand' => 'Apple',
                'image' => 'img/category/iphone14pro.png',
                'old_price' => 21000000,
                'price' => 19500000,
                'discount' => 7,
                'stock' => 'tersedia',
                'specs' => 'A16 Bionic, RAM 6GB, 128GB Storage',
                'category' => 'hp',
                'level' => 'flagship',
                'section' => 'product',
            ],
            [
                'name' => 'Xiaomi 13T Pro',
                'brand' => 'Xiaomi',
                'image' => 'img/category/xiaomi-13t.png',
                'old_price' => 9500000,
                'price' => 8800000,
                'discount' => 8,
                'stock' => 'tersedia',
                'specs' => 'Dimensity 9200+, RAM 12GB, 256GB Storage',
                'category' => 'hp',
                'level' => 'high range',
                'section' => 'promo',
            ],
            [
                'name' => 'Realme GT Neo 5',
                'brand' => 'Realme',
                'image' => 'img/category/realme-gtneo5.png',
                'old_price' => 7000000,
                'price' => 6500000,
                'discount' => 7,
                'stock' => 'tersedia',
                'specs' => 'Snapdragon 8+ Gen 1, RAM 8GB, 128GB',
                'category' => 'hp',
                'level' => 'mid range',
                'section' => 'promo',
            ],
            [
                'name' => 'Oppo Reno 10 Pro',
                'brand' => 'Oppo',
                'image' => 'img/category/oppo-reno10.png',
                'old_price' => 8000000,
                'price' => 7400000,
                'discount' => 8,
                'stock' => 'tersedia',
                'specs' => 'Snapdragon 778G, RAM 12GB, 256GB',
                'category' => 'hp',
                'level' => 'mid range',
                'section' => 'latest',
            ],
            [
                'name' => 'Vivo X90',
                'brand' => 'Vivo',
                'image' => 'img/category/vivo-x90.png',
                'old_price' => 11000000,
                'price' => 9990000,
                'discount' => 9,
                'stock' => 'tersedia',
                'specs' => 'Dimensity 9200, RAM 12GB, 256GB',
                'category' => 'hp',
                'level' => 'high range',
                'section' => 'product',
            ],
            [
                'name' => 'Asus ROG Phone 7',
                'brand' => 'Asus',
                'image' => 'img/category/rog-phone7.png',
                'old_price' => 16000000,
                'price' => 14900000,
                'discount' => 7,
                'stock' => 'tersedia',
                'specs' => 'Snapdragon 8 Gen 2, RAM 16GB, 512GB',
                'category' => 'hp',
                'level' => 'high range',
                'section' => 'product',
            ],
            [
                'name' => 'OnePlus 11',
                'brand' => 'OnePlus',
                'image' => 'img/category/oneplus-11.png',
                'old_price' => 12500000,
                'price' => 11500000,
                'discount' => 8,
                'stock' => 'tersedia',
                'specs' => 'Snapdragon 8 Gen 2, RAM 12GB, 256GB',
                'category' => 'hp',
                'level' => 'high range',
                'section' => 'latest',
            ],
            [
                'name' => 'Infinix Zero Ultra',
                'brand' => 'Infinix',
                'image' => 'img/category/infinix-zero-ultra.png',
                'old_price' => 6500000,
                'price' => 5900000,
                'discount' => 9,
                'stock' => 'tersedia',
                'specs' => 'Dimensity 920, RAM 8GB, 256GB',
                'category' => 'hp',
                'level' => 'mid range',
                'section' => 'product',
            ],
            [
                'name' => 'Tecno Phantom X2',
                'brand' => 'Tecno',
                'image' => 'img/category/tecno-phantomx2.png',
                'old_price' => 7000000,
                'price' => 6400000,
                'discount' => 8,
                'stock' => 'tersedia',
                'specs' => 'Dimensity 9000, RAM 8GB, 256GB',
                'category' => 'hp',
                'level' => 'mid range',
                'section' => 'product',
            ],

            // ================= LAPTOP =================
            [
                'name' => 'Asus ROG Strix G16',
                'brand' => 'Asus',
                'image' => 'img/category/asus-rog-g16.png',
                'old_price' => 23000000,
                'price' => 21500000,
                'discount' => 6,
                'stock' => 'tersedia',
                'specs' => 'Intel i9 13th Gen, RTX 4070, 16GB RAM, 1TB SSD',
                'category' => 'laptop',
                'level' => 'high range',
                'section' => 'recommendation',
            ],
            [
                'name' => 'MSI Katana 15',
                'brand' => 'MSI',
                'image' => 'img/category/msi-katana15.png',
                'old_price' => 20000000,
                'price' => 18500000,
                'discount' => 7,
                'stock' => 'tersedia',
                'specs' => 'Intel i7 13th Gen, RTX 4060, 16GB RAM, 512GB SSD',
                'category' => 'laptop',
                'level' => 'high range',
                'section' => 'recommendation',
            ],
            [
                'name' => 'Acer Nitro 5',
                'brand' => 'Acer',
                'image' => 'img/category/acer-nitro5.png',
                'old_price' => 18000000,
                'price' => 16500000,
                'discount' => 8,
                'stock' => 'tersedia',
                'specs' => 'AMD Ryzen 7, RTX 3060, 16GB RAM, 512GB SSD',
                'category' => 'laptop',
                'level' => 'high range',
                'section' => 'product',
            ],
            [
                'name' => 'Dell XPS 15',
                'brand' => 'Dell',
                'image' => 'img/category/dell-xps15.png',
                'old_price' => 30000000,
                'price' => 28000000,
                'discount' => 7,
                'stock' => 'tersedia',
                'specs' => 'Intel i9, RTX 4070, 32GB RAM, 1TB SSD',
                'category' => 'laptop',
                'level' => 'entry level',
                'section' => 'promo',
            ],
            [
                'name' => 'HP Omen 16',
                'brand' => 'HP',
                'image' => 'img/category/hp-omen16.png',
                'old_price' => 22000000,
                'price' => 20500000,
                'discount' => 7,
                'stock' => 'tersedia',
                'specs' => 'AMD Ryzen 9, RTX 4070, 32GB RAM, 1TB SSD',
                'category' => 'laptop',
                'level' => 'high range',
                'section' => 'latest',
            ],
            [
                'name' => 'Lenovo Legion 5 Pro',
                'brand' => 'Lenovo',
                'image' => 'img/category/lenovo-legion5.png',
                'old_price' => 21000000,
                'price' => 19500000,
                'discount' => 7,
                'stock' => 'tersedia',
                'specs' => 'AMD Ryzen 7, RTX 3070Ti, 16GB RAM, 1TB SSD',
                'category' => 'laptop',
                'level' => 'high range',
                'section' => 'product',
            ],
            [
                'name' => 'Apple MacBook Pro M2',
                'brand' => 'Apple',
                'image' => 'img/category/macbook-pro-m2.png',
                'old_price' => 35000000,
                'price' => 33500000,
                'discount' => 4,
                'stock' => 'tersedia',
                'specs' => 'Apple M2 Pro, 16GB RAM, 1TB SSD',
                'category' => 'laptop',
                'level' => 'entry level',
                'section' => 'latest',
            ],
            [
                'name' => 'Razer Blade 16',
                'brand' => 'Razer',
                'image' => 'img/category/razer-blade16.png',
                'old_price' => 40000000,
                'price' => 38500000,
                'discount' => 4,
                'stock' => 'tersedia',
                'specs' => 'Intel i9 13th Gen, RTX 4090, 32GB RAM, 1TB SSD',
                'category' => 'laptop',
                'level' => 'entry level',
                'section' => 'product',
            ],
            [
                'name' => 'Huawei MateBook X Pro',
                'brand' => 'Huawei',
                'image' => 'img/category/matebook-xpro.png',
                'old_price' => 27000000,
                'price' => 25500000,
                'discount' => 6,
                'stock' => 'tersedia',
                'specs' => 'Intel i7 12th Gen, 16GB RAM, 1TB SSD',
                'category' => 'laptop',
                'level' => 'flagship',
                'section' => 'product',
            ],
            [
                'name' => 'Microsoft Surface Laptop 5',
                'brand' => 'Microsoft',
                'image' => 'img/category/surface-laptop5.png',
                'old_price' => 28000000,
                'price' => 26500000,
                'discount' => 5,
                'stock' => 'tersedia',
                'specs' => 'Intel i7 12th Gen, 16GB RAM, 512GB SSD',
                'category' => 'laptop',
                'level' => 'flagship',
                'section' => 'latest',
            ],

            // ================= PC =================
            [
                'name' => 'Digital Alliance Templar X',
                'brand' => 'Digital Alliance',
                'image' => 'img/category/da-templarx.png',
                'old_price' => 17000000,
                'price' => 16000000,
                'discount' => 6,
                'stock' => 'tersedia',
                'specs' => 'Intel i7, RTX 3060Ti, 16GB RAM, 1TB SSD',
                'category' => 'pc',
                'level' => 'high range',
                'section' => 'product',
            ],
            [
                'name' => 'Alienware Aurora R15',
                'brand' => 'Alienware',
                'image' => 'img/category/alienware-r15.png',
                'old_price' => 50000000,
                'price' => 47000000,
                'discount' => 6,
                'stock' => 'tersedia',
                'specs' => 'Intel i9, RTX 4090, 64GB RAM, 2TB SSD',
                'category' => 'pc',
                'level' => 'flagship',
                'section' => 'product',
            ],
            [
                'name' => 'CyberPowerPC Gamer Xtreme',
                'brand' => 'CyberPowerPC',
                'image' => 'img/category/cyberpowerpc.png',
                'old_price' => 25000000,
                'price' => 23500000,
                'discount' => 6,
                'stock' => 'tersedia',
                'specs' => 'Intel i7, RTX 3070, 16GB RAM, 1TB SSD',
                'category' => 'pc',
                'level' => 'high range',
                'section' => 'product',
            ],
            [
                'name' => 'NZXT Streaming Plus PC',
                'brand' => 'NZXT',
                'image' => 'img/category/nzxt-stream.png',
                'old_price' => 28000000,
                'price' => 26500000,
                'discount' => 5,
                'stock' => 'tersedia',
                'specs' => 'AMD Ryzen 7, RTX 3070Ti, 16GB RAM, 1TB SSD',
                'category' => 'pc',
                'level' => 'high range',
                'section' => 'product',
            ],
            [
                'name' => 'Corsair Vengeance a7200',
                'brand' => 'Corsair',
                'image' => 'img/category/corsair-a7200.png',
                'old_price' => 35000000,
                'price' => 33000000,
                'discount' => 6,
                'stock' => 'tersedia',
                'specs' => 'AMD Ryzen 9, RTX 4080, 32GB RAM, 1TB SSD',
                'category' => 'pc',
                'level' => 'high range',
                'section' => 'recommendation',
            ],
            [
                'name' => 'HP Envy Desktop TE02',
                'brand' => 'HP',
                'image' => 'img/category/hp-envy.png',
                'old_price' => 22000000,
                'price' => 20500000,
                'discount' => 7,
                'stock' => 'tersedia',
                'specs' => 'Intel i7, RTX 3060, 16GB RAM, 1TB SSD',
                'category' => 'pc',
                'level' => 'mid range',
                'section' => 'promo',
            ],
            [
                'name' => 'Lenovo Legion Tower 7i',
                'brand' => 'Lenovo',
                'image' => 'img/category/legion-tower7.png',
                'old_price' => 28000000,
                'price' => 26500000,
                'discount' => 5,
                'stock' => 'tersedia',
                'specs' => 'Intel i9, RTX 3080, 32GB RAM, 1TB SSD',
                'category' => 'pc',
                'level' => 'high range',
                'section' => 'latest',
            ],
            [
                'name' => 'Asus ROG Strix G35',
                'brand' => 'Asus',
                'image' => 'img/category/rog-g35.png',
                'old_price' => 32000000,
                'price' => 30000000,
                'discount' => 6,
                'stock' => 'tersedia',
                'specs' => 'AMD Ryzen 9, RTX 3090, 32GB RAM, 1TB SSD',
                'category' => 'pc',
                'level' => 'high range',
                'section' => 'recommendation',
            ],
            [
                'name' => 'Dell Alienware Aurora Ryzen Edition',
                'brand' => 'Dell',
                'image' => 'img/category/alienware-ryzen.png',
                'old_price' => 34000000,
                'price' => 32000000,
                'discount' => 6,
                'stock' => 'tersedia',
                'specs' => 'AMD Ryzen 9, RTX 3080Ti, 32GB RAM, 1TB SSD',
                'category' => 'pc',
                'level' => 'flagship',
                'section' => 'product',
            ],
            [
                'name' => 'Gigabyte Aorus Model X',
                'brand' => 'Gigabyte',
                'image' => 'img/category/aorus-modelx.png',
                'old_price' => 38000000,
                'price' => 36000000,
                'discount' => 5,
                'stock' => 'tersedia',
                'specs' => 'Intel i9, RTX 4090, 64GB RAM, 2TB SSD',
                'category' => 'pc',
                'level' => 'flagship',
                'section' => 'product',
            ],

            // ================= ACCESSORIES =================
            [
                'name' => 'Rexus Gaming Headset HX10',
                'brand' => 'Rexus',
                'image' => 'img/category/rexus-hx10.png',
                'old_price' => 750000,
                'price' => 650000,
                'discount' => 13,
                'stock' => 'tersedia',
                'specs' => 'Driver 50mm, Surround 7.1, RGB',
                'category' => 'accessories',
                'level' => 'entry level',
                'section' => 'recommendation',
            ],
            [
                'name' => 'Logitech G502 X Plus',
                'brand' => 'Logitech',
                'image' => 'img/category/logitech-g502.png',
                'old_price' => 1500000,
                'price' => 1350000,
                'discount' => 10,
                'stock' => 'tersedia',
                'specs' => '25K DPI Sensor, RGB, Wireless',
                'category' => 'accessories',
                'level' => 'high range',
                'section' => 'promo',
            ],
            [
                'name' => 'SteelSeries Apex Pro TKL',
                'brand' => 'SteelSeries',
                'image' => 'img/category/apex-pro.png',
                'old_price' => 3500000,
                'price' => 3250000,
                'discount' => 7,
                'stock' => 'tersedia',
                'specs' => 'OmniPoint Adjustable Switches, RGB',
                'category' => 'accessories',
                'level' => 'entry level',
                'section' => 'product',
            ],
            [
                'name' => 'Razer Kraken V3',
                'brand' => 'Razer',
                'image' => 'img/category/razer-krakenv3.png',
                'old_price' => 1800000,
                'price' => 1650000,
                'discount' => 8,
                'stock' => 'tersedia',
                'specs' => '50mm Drivers, THX Spatial Audio, RGB',
                'category' => 'accessories',
                'level' => 'high range',
                'section' => 'product',
            ],
            [
                'name' => 'HyperX Cloud Alpha',
                'brand' => 'HyperX',
                'image' => 'img/category/hyperx-alpha.png',
                'old_price' => 2000000,
                'price' => 1850000,
                'discount' => 8,
                'stock' => 'tersedia',
                'specs' => 'Dual Chamber Drivers, Detachable Mic',
                'category' => 'accessories',
                'level' => 'high range',
                'section' => 'latest',
            ],
            [
                'name' => 'Corsair K70 RGB MK.2',
                'brand' => 'Corsair',
                'image' => 'img/category/corsair-k70.png',
                'old_price' => 2800000,
                'price' => 2600000,
                'discount' => 7,
                'stock' => 'tersedia',
                'specs' => 'Cherry MX Switches, RGB, USB Passthrough',
                'category' => 'accessories',
                'level' => 'entry level',
                'section' => 'product',
            ],
            [
                'name' => 'Cooler Master MM731',
                'brand' => 'Cooler Master',
                'image' => 'img/category/coolermaster-mm731.png',
                'old_price' => 1200000,
                'price' => 1100000,
                'discount' => 8,
                'stock' => 'tersedia',
                'specs' => 'PAW3370 Sensor, Wireless, RGB',
                'category' => 'accessories',
                'level' => 'mid range',
                'section' => 'product',
            ],
            [
                'name' => 'Redragon K552 Kumara',
                'brand' => 'Redragon',
                'image' => 'img/category/redragon-k552.png',
                'old_price' => 800000,
                'price' => 720000,
                'discount' => 10,
                'stock' => 'tersedia',
                'specs' => 'Outemu Blue Switch, TKL, RGB',
                'category' => 'accessories',
                'level' => 'entry level',
                'section' => 'product',
            ],
            [
                'name' => 'Fantech Helios XD3',
                'brand' => 'Fantech',
                'image' => 'img/category/fantech-xd3.png',
                'old_price' => 600000,
                'price' => 550000,
                'discount' => 8,
                'stock' => 'tersedia',
                'specs' => 'PixArt Sensor, Wireless, Lightweight',
                'category' => 'accessories',
                'level' => 'entry level',
                'section' => 'latest',
            ],
            [
                'name' => 'Keychron K6',
                'brand' => 'Keychron',
                'image' => 'img/category/keychron-k6.png',
                'old_price' => 1800000,
                'price' => 1650000,
                'discount' => 8,
                'stock' => 'tersedia',
                'specs' => 'Hot-swappable, Wireless, RGB',
                'category' => 'accessories',
                'level' => 'mid range',
                'section' => 'recommendation',
            ],
        ];

        DB::table('products')->insert($products);
    }
}
